package org.fresh.gd.commons.consts.pojo.dto.oauth;

import lombok.Data;

import java.util.Date;

@Data
public class AuthSysOrganizationDTO
{
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_organization.org_code
     *
     * @mbg.generated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_organization.org_name
     *
     * @mbg.generated
     */
    private String orgName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_organization.stat
     *
     * @mbg.generated
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_organization.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_organization.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    private String contact;
}
